# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Cuisine.create!(name: "American")
# Cuisine.create!(name: "Chinese")
# Cuisine.create!(name: "Thai")
# Cuisine.create!(name: "Italian")
# Cuisine.create!(name: "French")
# Cuisine.create!(name: "Japanese")
# Cuisine.create!(name: "Turkish")
# Cuisine.create!(name: "Korean")
# Cuisine.create!(name: "Vietnamese")
# Cuisine.create!(name: "Indian")
# Cuisine.create!(name: "Spanish")
# Cuisine.create!(name: "Greek")
# Cuisine.create!(name: "Mexican")
# Cuisine.create!(name: "Malaysian")
# Cuisine.create!(name: "African")
# Cuisine.create!(name: "German")
# Cuisine.create!(name: "Indonesian")
# Cuisine.create!(name: "Russian")
# Cuisine.create!(name: "Other")

# Restaurant.create!(name: 'Herbed Delicious', customer_rating: 4, distance: 7, price: 20, cuisine_id: 9)
# Restaurant.create!(name: 'Deliciousscape', customer_rating: 3, distance: 7, price: 50, cuisine_id: 1)
# Restaurant.create!(name: 'Hideaway Delicious', customer_rating: 2, distance: 5, price: 40, cuisine_id: 12)
# Restaurant.create!(name: 'Cuts Delicious', customer_rating: 3, distance: 9, price: 25, cuisine_id: 8)
# Restaurant.create!(name: 'Lord Delicious', customer_rating: 1, distance: 7, price: 35, cuisine_id: 18)
# Restaurant.create!(name: 'Hilltop Delicious', customer_rating: 3, distance: 3, price: 45, cuisine_id: 6)
# Restaurant.create!(name: 'Fine Delicious', customer_rating: 4, distance: 5, price: 45, cuisine_id: 4)
# Restaurant.create!(name: 'Deliciousish', customer_rating: 1, distance: 3, price: 50, cuisine_id: 12)
# Restaurant.create!(name: 'Havana Delicious', customer_rating: 3, distance: 1, price: 35, cuisine_id: 8)
# Restaurant.create!(name: 'Deliciouspad', customer_rating: 3, distance: 10, price: 40, cuisine_id: 13)
# Restaurant.create!(name: 'Deliciousbea', customer_rating: 5, distance: 6, price: 50, cuisine_id: 15)
# Restaurant.create!(name: 'Deliciousquipo', customer_rating: 2, distance: 2, price: 10, cuisine_id: 19)
# Restaurant.create!(name: 'Fed Delicious', customer_rating: 2, distance: 9, price: 35, cuisine_id: 4)
# Restaurant.create!(name: 'Hotspot Delicious', customer_rating: 4, distance: 10, price: 25, cuisine_id: 13)
# Restaurant.create!(name: 'Gusto Delicious', customer_rating: 5, distance: 3, price: 50, cuisine_id: 2)
# Restaurant.create!(name: 'Deliciouszen', customer_rating: 2, distance: 6, price: 30, cuisine_id: 5)
# Restaurant.create!(name: 'Deliciouszilla', customer_rating: 4, distance: 1, price: 15, cuisine_id: 2)
# Restaurant.create!(name: 'Deliciousio', customer_rating: 5, distance: 9, price: 40, cuisine_id: 19)
# Restaurant.create!(name: 'Local Delicious', customer_rating: 5, distance: 4, price: 20, cuisine_id: 12)
# Restaurant.create!(name: 'Crisp Delicious', customer_rating: 5, distance: 2, price: 45, cuisine_id: 18)
# Restaurant.create!(name: 'Deliciousoryx', customer_rating: 1, distance: 5, price: 25, cuisine_id: 2)
# Restaurant.create!(name: 'Bang Delicious', customer_rating: 5, distance: 2, price: 15, cuisine_id: 18)
# Restaurant.create!(name: 'Deliciouszoid', customer_rating: 3, distance: 2, price: 30, cuisine_id: 4)
# Restaurant.create!(name: 'Hearty ChowClick', customer_rating: 2, distance: 6, price: 25, cuisine_id: 8)
# Restaurant.create!(name: 'Traditional Chow', customer_rating: 5, distance: 2, price: 15, cuisine_id: 11)
# Restaurant.create!(name: 'Bash Chow', customer_rating: 2, distance: 6, price: 45, cuisine_id: 9)
# Restaurant.create!(name: 'Minty Chow', customer_rating: 4, distance: 8, price: 35, cuisine_id: 5)
# Restaurant.create!(name: 'Chowaza', customer_rating: 3, distance: 9, price: 20, cuisine_id: 12)
# Restaurant.create!(name: 'Lucha Chow', customer_rating: 3, distance: 4, price: 25, cuisine_id: 14)
# Restaurant.create!(name: 'Hut Chow', customer_rating: 2, distance: 2, price: 10, cuisine_id: 3)
# Restaurant.create!(name: 'Wish Chow', customer_rating: 3, distance: 1, price: 40, cuisine_id: 1)
# Restaurant.create!(name: 'Chowish', customer_rating: 3, distance: 8, price: 10, cuisine_id: 19)
# Restaurant.create!(name: 'Bazaar Chow', customer_rating: 4, distance: 4, price: 40, cuisine_id: 1)
# Restaurant.create!(name: 'Story Chow', customer_rating: 2, distance: 10, price: 30, cuisine_id: 19)
# Restaurant.create!(name: 'Hideout Chow', customer_rating: 2, distance: 7, price: 10, cuisine_id: 15)
# Restaurant.create!(name: 'Strip Chow', customer_rating: 5, distance: 9, price: 35, cuisine_id: 19)
# Restaurant.create!(name: 'Aroma Chow', customer_rating: 5, distance: 10, price: 10, cuisine_id: 18)
# Restaurant.create!(name: 'Chowology', customer_rating: 5, distance: 9, price: 30, cuisine_id: 6)
# Restaurant.create!(name: 'Chowify', customer_rating: 4, distance: 4, price: 45, cuisine_id: 2)
# Restaurant.create!(name: 'Piece Chow', customer_rating: 4, distance: 9, price: 10, cuisine_id: 13)
# Restaurant.create!(name: 'Cave Chow', customer_rating: 3, distance: 4, price: 40, cuisine_id: 6)
# Restaurant.create!(name: 'Wagon Chow', customer_rating: 3, distance: 9, price: 10, cuisine_id: 1)
# Restaurant.create!(name: 'Choworyx', customer_rating: 2, distance: 3, price: 40, cuisine_id: 7)
# Restaurant.create!(name: 'Whole Chow', customer_rating: 2, distance: 7, price: 15, cuisine_id: 4)
# Restaurant.create!(name: 'Central Chow', customer_rating: 3, distance: 7, price: 45, cuisine_id: 1)
# Restaurant.create!(name: 'Ambrosial Chow', customer_rating: 4, distance: 5, price: 50, cuisine_id: 15)
# Restaurant.create!(name: 'Place Chow', customer_rating: 2, distance: 2, price: 15, cuisine_id: 11)
# Restaurant.create!(name: 'Reservation Table', customer_rating: 4, distance: 3, price: 20, cuisine_id: 13)
# Restaurant.create!(name: 'Chopped Table', customer_rating: 1, distance: 5, price: 40, cuisine_id: 3)
# Restaurant.create!(name: 'Herbed Table', customer_rating: 1, distance: 1, price: 15, cuisine_id: 12)
# Restaurant.create!(name: 'Palate Table', customer_rating: 1, distance: 1, price: 15, cuisine_id: 14)
# Restaurant.create!(name: 'Grove Table', customer_rating: 5, distance: 2, price: 10, cuisine_id: 13)
# Restaurant.create!(name: 'Fodder Table', customer_rating: 4, distance: 1, price: 20, cuisine_id: 8)
# Restaurant.create!(name: 'Tablebes', customer_rating: 4, distance: 2, price: 40, cuisine_id: 13)
# Restaurant.create!(name: 'Chow Table', customer_rating: 1, distance: 1, price: 10, cuisine_id: 2)
# Restaurant.create!(name: 'Bay Table', customer_rating: 3, distance: 7, price: 50, cuisine_id: 18)
# Restaurant.create!(name: 'Tablebea', customer_rating: 1, distance: 7, price: 25, cuisine_id: 10)
# Restaurant.create!(name: 'Fine Table', customer_rating: 2, distance: 5, price: 15, cuisine_id: 12)
# Restaurant.create!(name: 'Cellar Table', customer_rating: 4, distance: 8, price: 25, cuisine_id: 8)
# Restaurant.create!(name: 'Boy Table', customer_rating: 3, distance: 9, price: 30, cuisine_id: 13)
# Restaurant.create!(name: 'Tableomatic', customer_rating: 1, distance: 5, price: 20, cuisine_id: 16)
# Restaurant.create!(name: 'Tableque', customer_rating: 4, distance: 3, price: 10, cuisine_id: 4)
# Restaurant.create!(name: 'Tableio', customer_rating: 3, distance: 3, price: 40, cuisine_id: 1)
# Restaurant.create!(name: 'Tableoont', customer_rating: 5, distance: 10, price: 20, cuisine_id: 12)
# Restaurant.create!(name: 'Tableadora', customer_rating: 5, distance: 2, price: 25, cuisine_id: 8)
# Restaurant.create!(name: 'Tableooze', customer_rating: 3, distance: 1, price: 50, cuisine_id: 16)
# Restaurant.create!(name: 'Garnish Table', customer_rating: 4, distance: 9, price: 40, cuisine_id: 4)
# Restaurant.create!(name: 'Brew Table', customer_rating: 2, distance: 10, price: 15, cuisine_id: 8)
# Restaurant.create!(name: 'Hotspot Table', customer_rating: 3, distance: 7, price: 40, cuisine_id: 15)
# Restaurant.create!(name: 'Fresh Table', customer_rating: 3, distance: 2, price: 30, cuisine_id: 1)
# Restaurant.create!(name: 'Appetite Table', customer_rating: 1, distance: 10, price: 40, cuisine_id: 8)
# Restaurant.create!(name: 'Cave Tasty', customer_rating: 5, distance: 10, price: 15, cuisine_id: 18)
# Restaurant.create!(name: 'Whole Tasty', customer_rating: 1, distance: 1, price: 30, cuisine_id: 5)
# Restaurant.create!(name: 'Tastyio', customer_rating: 3, distance: 10, price: 30, cuisine_id: 14)
# Restaurant.create!(name: 'Lane Tasty', customer_rating: 5, distance: 5, price: 35, cuisine_id: 2)
# Restaurant.create!(name: 'Nouveau Tasty', customer_rating: 1, distance: 9, price: 50, cuisine_id: 9)
# Restaurant.create!(name: 'Relish Tasty', customer_rating: 3, distance: 8, price: 50, cuisine_id: 13)
# Restaurant.create!(name: 'Tastyooze', customer_rating: 3, distance: 6, price: 20, cuisine_id: 11)
# Restaurant.create!(name: 'Binge Tasty', customer_rating: 1, distance: 8, price: 10, cuisine_id: 4)
# Restaurant.create!(name: 'Fed Tasty', customer_rating: 3, distance: 5, price: 25, cuisine_id: 2)
# Restaurant.create!(name: 'Diced Tasty', customer_rating: 5, distance: 4, price: 40, cuisine_id: 7)
# Restaurant.create!(name: 'Tastylux', customer_rating: 5, distance: 8, price: 35, cuisine_id: 14)
# Restaurant.create!(name: 'Tastyaza', customer_rating: 3, distance: 7, price: 45, cuisine_id: 18)
# Restaurant.create!(name: 'Grill Tasty', customer_rating: 2, distance: 2, price: 30, cuisine_id: 2)
# Restaurant.create!(name: 'Tastyopolis', customer_rating: 1, distance: 6, price: 20, cuisine_id: 8)
# Restaurant.create!(name: 'Stand Tasty', customer_rating: 4, distance: 3, price: 40, cuisine_id: 16)
# Restaurant.create!(name: 'Feast Tasty', customer_rating: 2, distance: 8, price: 20, cuisine_id: 18)
# Restaurant.create!(name: 'Baby Tasty', customer_rating: 3, distance: 1, price: 20, cuisine_id: 8)
# Restaurant.create!(name: 'Fodder Tasty', customer_rating: 4, distance: 4, price: 30, cuisine_id: 9)
# Restaurant.create!(name: 'Takeout Tasty', customer_rating: 5, distance: 5, price: 20, cuisine_id: 11)
# Restaurant.create!(name: 'Wrap Tasty', customer_rating: 1, distance: 10, price: 30, cuisine_id: 4)
# Restaurant.create!(name: 'Tastylia', customer_rating: 3, distance: 4, price: 50, cuisine_id: 3)
# Restaurant.create!(name: 'Havana Tasty', customer_rating: 4, distance: 10, price: 15, cuisine_id: 11)
# Restaurant.create!(name: 'Crumb Tasty', customer_rating: 2, distance: 5, price: 25, cuisine_id: 11)
# Restaurant.create!(name: 'Dished Tasty', customer_rating: 1, distance: 7, price: 25, cuisine_id: 18)
# Restaurant.create!(name: 'Chop Grill', customer_rating: 5, distance: 8, price: 10, cuisine_id: 17)
# Restaurant.create!(name: 'Festive Grill', customer_rating: 2, distance: 4, price: 35, cuisine_id: 6)
# Restaurant.create!(name: 'Me Grill', customer_rating: 5, distance: 5, price: 25, cuisine_id: 9)
# Restaurant.create!(name: 'Lounge Grill', customer_rating: 3, distance: 10, price: 40, cuisine_id: 5)
# Restaurant.create!(name: 'Coastal Grill', customer_rating: 2, distance: 7, price: 10, cuisine_id: 17)
# Restaurant.create!(name: 'Perfection Grill', customer_rating: 3, distance: 3, price: 50, cuisine_id: 7)
# Restaurant.create!(name: 'Hungry Grill', customer_rating: 3, distance: 4, price: 50, cuisine_id: 9)
# Restaurant.create!(name: 'Cater Grill', customer_rating: 4, distance: 3, price: 50, cuisine_id: 5)
# Restaurant.create!(name: 'Presto Grill', customer_rating: 5, distance: 2, price: 40, cuisine_id: 15)
# Restaurant.create!(name: 'Crispy Grill', customer_rating: 1, distance: 7, price: 45, cuisine_id: 19)
# Restaurant.create!(name: 'Grilltastic', customer_rating: 3, distance: 3, price: 30, cuisine_id: 14)
# Restaurant.create!(name: 'Grillsio', customer_rating: 3, distance: 4, price: 15, cuisine_id: 19)
# Restaurant.create!(name: 'Tasteful Grill', customer_rating: 5, distance: 9, price: 10, cuisine_id: 2)
# Restaurant.create!(name: 'Yummy Grill', customer_rating: 1, distance: 8, price: 50, cuisine_id: 15)
# Restaurant.create!(name: 'Crisp Grill', customer_rating: 2, distance: 6, price: 50, cuisine_id: 19)
# Restaurant.create!(name: 'Grillya', customer_rating: 2, distance: 7, price: 40, cuisine_id: 13)
# Restaurant.create!(name: 'Cuts Grill', customer_rating: 1, distance: 7, price: 30, cuisine_id: 8)
# Restaurant.create!(name: 'Grillarc', customer_rating: 2, distance: 3, price: 25, cuisine_id: 13)
# Restaurant.create!(name: 'Wish Grill', customer_rating: 1, distance: 8, price: 30, cuisine_id: 3)
# Restaurant.create!(name: 'Dished Grill', customer_rating: 3, distance: 1, price: 10, cuisine_id: 8)
# Restaurant.create!(name: 'Divine Grill', customer_rating: 1, distance: 9, price: 25, cuisine_id: 7)
# Restaurant.create!(name: 'Wedge Grill', customer_rating: 2, distance: 4, price: 35, cuisine_id: 2)
# Restaurant.create!(name: 'Gusto Grill', customer_rating: 3, distance: 10, price: 10, cuisine_id: 3)
# Restaurant.create!(name: 'Chef Grill', customer_rating: 5, distance: 4, price: 35, cuisine_id: 19)
# Restaurant.create!(name: 'Grove Palace', customer_rating: 2, distance: 4, price: 20, cuisine_id: 1)
# Restaurant.create!(name: 'Tasteful Palace', customer_rating: 2, distance: 3, price: 20, cuisine_id: 12)
# Restaurant.create!(name: 'Perfection Palace', customer_rating: 3, distance: 1, price: 20, cuisine_id: 3)
# Restaurant.create!(name: 'Palaceio', customer_rating: 4, distance: 7, price: 45, cuisine_id: 14)
# Restaurant.create!(name: 'Palaceado', customer_rating: 3, distance: 6, price: 25, cuisine_id: 4)
# Restaurant.create!(name: 'Flavor Palace', customer_rating: 2, distance: 2, price: 20, cuisine_id: 14)
# Restaurant.create!(name: 'Palaceadri', customer_rating: 4, distance: 8, price: 50, cuisine_id: 11)
# Restaurant.create!(name: 'Hotspot Palace', customer_rating: 1, distance: 3, price: 35, cuisine_id: 3)
# Restaurant.create!(name: 'Palaceopedia', customer_rating: 5, distance: 10, price: 25, cuisine_id: 8)
# Restaurant.create!(name: 'Gusto Palace', customer_rating: 5, distance: 10, price: 30, cuisine_id: 9)
# Restaurant.create!(name: 'Feed Palace', customer_rating: 2, distance: 5, price: 20, cuisine_id: 7)
# Restaurant.create!(name: 'Smash Palace', customer_rating: 1, distance: 9, price: 10, cuisine_id: 1)
# Restaurant.create!(name: 'Gnaw Palace', customer_rating: 1, distance: 3, price: 50, cuisine_id: 13)
# Restaurant.create!(name: 'Dished Palace', customer_rating: 5, distance: 7, price: 25, cuisine_id: 5)
# Restaurant.create!(name: 'Spicy Palace', customer_rating: 2, distance: 6, price: 10, cuisine_id: 9)
# Restaurant.create!(name: 'Nouveau Palace', customer_rating: 3, distance: 8, price: 15, cuisine_id: 4)
# Restaurant.create!(name: 'Relish Palace', customer_rating: 2, distance: 3, price: 40, cuisine_id: 9)
# Restaurant.create!(name: 'Palaceistic', customer_rating: 2, distance: 10, price: 45, cuisine_id: 9)
# Restaurant.create!(name: 'Palacearo', customer_rating: 1, distance: 4, price: 50, cuisine_id: 4)
# Restaurant.create!(name: 'Place Palace', customer_rating: 5, distance: 2, price: 40, cuisine_id: 17)
# Restaurant.create!(name: 'Aroma Palace', customer_rating: 2, distance: 5, price: 40, cuisine_id: 1)
# Restaurant.create!(name: 'Fury Palace', customer_rating: 5, distance: 3, price: 30, cuisine_id: 17)
# Restaurant.create!(name: 'Palacex', customer_rating: 2, distance: 6, price: 15, cuisine_id: 18)
# Restaurant.create!(name: 'Palaceocity', customer_rating: 1, distance: 7, price: 25, cuisine_id: 15)
# Restaurant.create!(name: 'Ambrosial Yummy', customer_rating: 3, distance: 7, price: 50, cuisine_id: 17)
# Restaurant.create!(name: 'Nibble Yummy', customer_rating: 1, distance: 8, price: 15, cuisine_id: 2)
# Restaurant.create!(name: 'Accent Yummy', customer_rating: 5, distance: 3, price: 40, cuisine_id: 17)
# Restaurant.create!(name: 'Yummylia', customer_rating: 1, distance: 1, price: 40, cuisine_id: 5)
# Restaurant.create!(name: 'Hotspot Yummy', customer_rating: 1, distance: 3, price: 45, cuisine_id: 17)
# Restaurant.create!(name: 'Chef Yummy', customer_rating: 4, distance: 9, price: 10, cuisine_id: 12)
# Restaurant.create!(name: 'Acclaimed Yummy', customer_rating: 5, distance: 8, price: 50, cuisine_id: 8)
# Restaurant.create!(name: 'Yummyella', customer_rating: 2, distance: 3, price: 40, cuisine_id: 6)
# Restaurant.create!(name: 'Palace Yummy', customer_rating: 4, distance: 2, price: 50, cuisine_id: 19)
# Restaurant.create!(name: 'Sizzle Yummy', customer_rating: 3, distance: 1, price: 15, cuisine_id: 18)
# Restaurant.create!(name: 'Galore Yummy', customer_rating: 2, distance: 9, price: 40, cuisine_id: 9)
# Restaurant.create!(name: 'Yummyquipo', customer_rating: 2, distance: 3, price: 45, cuisine_id: 7)
# Restaurant.create!(name: 'Divine Yummy', customer_rating: 1, distance: 10, price: 25, cuisine_id: 13)
# Restaurant.create!(name: 'Aladdin Yummy', customer_rating: 1, distance: 4, price: 30, cuisine_id: 15)
# Restaurant.create!(name: 'Yummyscape', customer_rating: 1, distance: 3, price: 35, cuisine_id: 13)
# Restaurant.create!(name: 'Yummylance', customer_rating: 1, distance: 9, price: 10, cuisine_id: 6)
# Restaurant.create!(name: 'Crisp Yummy', customer_rating: 1, distance: 10, price: 25, cuisine_id: 13)
# Restaurant.create!(name: 'Cantina Yummy', customer_rating: 5, distance: 6, price: 20, cuisine_id: 18)
# Restaurant.create!(name: 'Cellar Yummy', customer_rating: 2, distance: 8, price: 50, cuisine_id: 6)
# Restaurant.create!(name: 'Festive Yummy', customer_rating: 2, distance: 2, price: 25, cuisine_id: 15)
# Restaurant.create!(name: 'Upscale Yummy', customer_rating: 2, distance: 10, price: 45, cuisine_id: 11)
# Restaurant.create!(name: 'Lucha Yummy', customer_rating: 1, distance: 10, price: 40, cuisine_id: 3)
# Restaurant.create!(name: 'Diced Yummy', customer_rating: 5, distance: 3, price: 20, cuisine_id: 14)
# Restaurant.create!(name: 'Factory Yummy', customer_rating: 4, distance: 3, price: 15, cuisine_id: 13)
# Restaurant.create!(name: 'Dude Kitchen', customer_rating: 4, distance: 10, price: 35, cuisine_id: 5)
# Restaurant.create!(name: 'Kitchengenics', customer_rating: 4, distance: 3, price: 20, cuisine_id: 8)
# Restaurant.create!(name: 'Galore Kitchen', customer_rating: 5, distance: 10, price: 45, cuisine_id: 11)
# Restaurant.create!(name: 'Story Kitchen', customer_rating: 5, distance: 3, price: 20, cuisine_id: 15)
# Restaurant.create!(name: 'Kitchenbia', customer_rating: 2, distance: 1, price: 30, cuisine_id: 12)
# Restaurant.create!(name: 'Fuel Kitchen', customer_rating: 4, distance: 7, price: 40, cuisine_id: 2)
# Restaurant.create!(name: 'Dished Kitchen', customer_rating: 5, distance: 3, price: 30, cuisine_id: 14)
# Restaurant.create!(name: 'Kitchenish', customer_rating: 3, distance: 2, price: 20, cuisine_id: 6)
# Restaurant.create!(name: 'Bang Kitchen', customer_rating: 1, distance: 1, price: 40, cuisine_id: 11)
# Restaurant.create!(name: 'Bit Kitchen', customer_rating: 1, distance: 1, price: 30, cuisine_id: 18)
# Restaurant.create!(name: 'Kitchenlia', customer_rating: 2, distance: 7, price: 50, cuisine_id: 1)
# Restaurant.create!(name: 'Kitchenster', customer_rating: 2, distance: 1, price: 10, cuisine_id: 1)
# Restaurant.create!(name: 'Devine Kitchen', customer_rating: 3, distance: 9, price: 30, cuisine_id: 16)
# Restaurant.create!(name: 'Connoisseur Kitchen', customer_rating: 2, distance: 6, price: 30, cuisine_id: 19)
# Restaurant.create!(name: 'Munchies Kitchen', customer_rating: 5, distance: 5, price: 45, cuisine_id: 9)
# Restaurant.create!(name: 'Fine Kitchen', customer_rating: 2, distance: 10, price: 20, cuisine_id: 17)
# Restaurant.create!(name: 'Crisp Kitchen', customer_rating: 1, distance: 3, price: 35, cuisine_id: 2)
# Restaurant.create!(name: 'Hut Kitchen', customer_rating: 3, distance: 5, price: 10, cuisine_id: 17)
# Restaurant.create!(name: 'Kitchenvio', customer_rating: 3, distance: 1, price: 50, cuisine_id: 12)
# Restaurant.create!(name: 'Kitchenarc', customer_rating: 2, distance: 5, price: 10, cuisine_id: 15)
# Restaurant.create!(name: 'Kitchenry', customer_rating: 4, distance: 6, price: 40, cuisine_id: 11)
# Restaurant.create!(name: 'Safety Kitchen', customer_rating: 2, distance: 4, price: 20, cuisine_id: 6)
# Restaurant.create!(name: 'Smash Kitchen', customer_rating: 1, distance: 2, price: 50, cuisine_id: 7)
# Restaurant.create!(name: 'Brew Kitchen', customer_rating: 2, distance: 4, price: 40, cuisine_id: 18)
# Restaurant.create!(name: 'Connoisseur Bar', customer_rating: 2, distance: 2, price: 25, cuisine_id: 17)
# Restaurant.create!(name: 'Bariva', customer_rating: 5, distance: 10, price: 40, cuisine_id: 10)
# Restaurant.create!(name: 'Barscape', customer_rating: 3, distance: 4, price: 15, cuisine_id: 4)
# Restaurant.create!(name: 'Hot Bar', customer_rating: 4, distance: 4, price: 20, cuisine_id: 2)
# Restaurant.create!(name: 'Place Bar', customer_rating: 3, distance: 5, price: 50, cuisine_id: 13)
# Restaurant.create!(name: 'Grill Bar', customer_rating: 1, distance: 9, price: 40, cuisine_id: 5)
# Restaurant.create!(name: 'Dine Bar', customer_rating: 5, distance: 10, price: 35, cuisine_id: 15)
# Restaurant.create!(name: 'Wave Bar', customer_rating: 4, distance: 8, price: 20, cuisine_id: 3)
